name: Maven site report publishing
on:
  workflow_dispatch:
    inputs:
      trigger-repository:
        required: true
      trigger-ref:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout '${{github.event.inputs.trigger-repository}}' repository
        uses: actions/checkout@v2
        with:
          repository: ${{github.event.inputs.trigger-repository}}
          ref: ${{github.event.inputs.trigger-ref}}
          path: __artifact
          fetch-depth: 0

      - name: Generate Maven site report
        run: |
          cd __artifact && \
            mvn --batch-mode site
