name: Publish Maven site report
on:
  workflow_dispatch:
    inputs:
      trigger-repository:
        required: true
      trigger-ref:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout '${{github.repository}}' repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout '${{github.event.inputs.trigger-repository}}' repository
        uses: actions/checkout@v2
        with:
          repository: ${{github.event.inputs.trigger-repository}}
          ref: ${{github.event.inputs.trigger-ref}}
          path: .local/artifact
          fetch-depth: 0

      - name: Generate Maven site report
        run: |
          MAVEN_VERSION=$( \
            mvn \
              exec:exec \
                --file .local/artifact/pom.xml \
                --non-recursive \
                --quiet \
                -Dexec.executable=echo \
                -Dexec.args='${project.version}' \
          )
          rm -rf "projects/${{github.event.inputs.trigger-repository}}/${MAVEN_VERSION}"
          mkdir -p "projects/${{github.event.inputs.trigger-repository}}/${MAVEN_VERSION}"
          mvn --batch-mode --file .local/artifact/pom.xml site
          cp -R .local/artifact/target/site/* "projects/${{github.event.inputs.trigger-repository}}/${MAVEN_VERSION}/"
          git add . -A
          git commit -m "Maven site report published for ${{github.event.inputs.trigger-repository}}:${MAVEN_VERSION}"

